In [94]:
import numpy as np
from numpy import linalg

**Задание 1**<br> Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [86]:
def narray(n):
    l = list()
    for i in range(n):
        l.append(i) 
    return np.array(list(reversed(l)))

In [87]:
narray(13)

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

**Задание 2**<br> Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [88]:
def diag_matrix(n):
    na = narray(n)
    return np.diag(na,0)

In [89]:
def sum_diag_matrix(n):
    return sum(diag_matrix(n).diagonal())

In [90]:
diag_matrix(4)

array([[3, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [91]:
sum_diag_matrix(4)

6

**Задание 3**<br> Решите систему уравнений:
<br>$4x + 2y + z = 4$</br>
<br>$x + 3y = 12$</br>
<br>$5y + 4z = -3$</br>

In [102]:
matrix = np.array([[4,2,1],[1,3,0],[0,5,4]])

In [103]:
response = np.array([4,12,-3])

In [104]:
linalg.solve(matrix, response)

array([ 0.46666667,  3.84444444, -5.55555556])